TweenLite.to($facebook,0,{css:{"marginLeft":-70}});TweenLite.to($twitter,0,{css:{"marginLeft":-70}});TweenLite.to($google,0,{css:{"marginLeft":-70}});TweenLite.to($pinterest,0,{css:{"marginLeft":-70}});TweenLite.to($facebook,.3,{delay:0.1,css:{"marginLeft":0},ease:Back.easeOut});TweenLite.to($twitter,.3,{delay:0.2,css:{"marginLeft":0},ease:Back.easeOut});TweenLite.to($google,.3,{delay:0.3,css:{"marginLeft":0},ease:Back.easeOut});TweenLite.to($pinterest,.3,{delay:0.4,css:{"marginLeft":0},ease:Back.easeOut});$left.show();$facebook.on('click',onFacebook);$twitter.on('click',onTwitter);$google.on('click',onGoogle);$pinterest.on('click',onPinterest);}
function hide(){$facebook.off('click',onFacebook);$twitter.off('click',onTwitter);$google.off('click',onGoogle);$pinterest.off('click',onPinterest);TweenLite.to($facebook,.3,{css:{"marginLeft":-70},ease:Back.easeIn});TweenLite.to($twitter,.3,{delay:0.1,css:{"marginLeft":-70},ease:Back.easeIn});TweenLite.to($google,.3,{delay:0.2,css:{"marginLeft":-70},ease:Back.easeIn});TweenLite.to($pinterest,.3,{delay:0.3,css:{"marginLeft":-70},ease:Back.easeIn});}
function remove(){$facebook.off('click',onFacebook);$twitter.off('click',onTwitter);$google.off('click',onGoogle);$pinterest.off('click',onPinterest);TweenLite.killTweensOf($facebook);TweenLite.killTweensOf($twitter);TweenLite.killTweensOf($google);TweenLite.killTweensOf($pinterest);TweenLite.to($facebook,0,{css:{"marginLeft":-70}});TweenLite.to($twitter,0,{css:{"marginLeft":-70}});TweenLite.to($google,0,{css:{"marginLeft":-70}});TweenLite.to($pinterest,0,{css:{"marginLeft":-70}});}
function onFacebook(){var poster=CMDetect.SITE_URL+ConfigModel.configArr[_curIndex].poster.img+'_t.jpg',title=CMDetect.SITE_TITLE+" - "+ConfigModel.configArr[_curIndex].poster.title,url=CMDetect.SITE_URL+"#!/section/"+ConfigModel.configArr[_curIndex].poster.id,php_url=CMDetect.SITE_URL+"share.php?url="+encodeURIComponent(url)+"&title="+encodeURIComponent(title)+"&poster="+encodeURIComponent(poster),share_url="https://www.facebook.com/dialog/feed?app_id="+CMDetect.APP_ID+"&link="+encodeURIComponent(php_url)+"&picture="+encodeURIComponent(poster)+"&name="+encodeURIComponent(title)+"&caption="+encodeURIComponent(url)+"&description="+encodeURIComponent(CMDetect.SITE_DES)+"&redirect_uri="+encodeURIComponent(CMDetect.SITE_URL+"close.html")+"&display=popup";CMUtiles.openPopup(share_url,"",600,500);}
function onTwitter(){var title=CMDetect.SITE_TITLE+" - "+ConfigModel.configArr[_curIndex].poster.title,url=CMDetect.SITE_URL+"#!/section/"+ConfigModel.configArr[_curIndex].poster.id,share_url="http://twitter.com/share?url="+encodeURIComponent(url)+"&text="+encodeURIComponent(title);CMUtiles.openPopup(share_url,"",600,260);}
function onGoogle(){var poster=CMDetect.SITE_URL+ConfigModel.configArr[_curIndex].poster.img+'_t.jpg',title=CMDetect.SITE_TITLE+" - "+ConfigModel.configArr[_curIndex].poster.title,url=CMDetect.SITE_URL+"#!/section/"+ConfigModel.configArr[_curIndex].poster.id,php_url=CMDetect.SITE_URL+"share.php?url="+encodeURIComponent(url)+"&title="+encodeURIComponent(title)+"&poster="+encodeURIComponent(poster),share_url="https://plus.google.com/share?url="+encodeURIComponent(php_url);CMUtiles.openPopup(share_url,"",600,400);}
function onPinterest(){var poster=CMDetect.SITE_URL+ConfigModel.configArr[_curIndex].poster.img+'_b.jpg',title=CMDetect.SITE_TITLE+" - "+ConfigModel.configArr[_curIndex].poster.title,url=CMDetect.SITE_URL+"#!/section/"+ConfigModel.configArr[_curIndex].poster.id,share_url='http://pinterest.com/pin/create/button/?url='+encodeURIComponent(url)
+'&media='+encodeURIComponent(poster)
+'&description='+encodeURIComponent(title);CMUtiles.openPopup(share_url,"",700,300);}

return{show:show,hide:hide,remove:remove}})();;var ShareTooltip=ShareTooltip||(function(){var _isShow,$share,$html='<div id="foot-share-box">'+'<div id="foot-share-0" class="foot-share-item"></div>'+'<div id="foot-share-1" class="foot-share-item"></div>'+'<div id="foot-share-2" class="foot-share-item"></div>'+'<div id="foot-share-3" class="foot-share-item"></div>'+'<div id="foot-share-4" class="foot-share-item"></div>'+'<div id="foot-share-5" class="foot-share-item"></div></div>';function init(){_isShow=false;$share=$('#foot-sharecon');$share.html($html);$('#foot-share-box').on('mouseenter',shareOver).on('mouseleave',shareOut);$('#foot-share-0').on('click',onShare0);$('#foot-share-1').on('click',onShare1);$('#foot-share-2').on('click',onShare2);$('#foot-share-3').on('click',onShare3);$('#foot-share-4').on('click',onShare4);$('#foot-share-5').on('click',onShare5);}
fu




https://www.facebook.com/dialog/feed?app_id=304280369692789&link=http%3A%2F%2Ffff.cmiscm.com%2Fshare.php%3Furl%3Dhttp%253A%252F%252Ffff.cmiscm.com%252F%2523!%252Fsection%252Fspiral%26title%3DForm%2520Follows%2520Function%2520-%2520Spiral%26poster%3Dhttp%253A%252F%252Ffff.cmiscm.com%252Fdata%252Fposter%252Fspiral_t.jpg&picture=http%3A%2F%2Ffff.cmiscm.com%2Fdata%2Fposter%2Fspiral_t.jpg&name=Form%20Follows%20Function%20-%20Spiral&caption=http%3A%2F%2Ffff.cmiscm.com%2F%23!%2Fsection%2Fspiral&description=FFF%20is%20a%20collection%20of%20interactive%20experiences.%20Each%20experience%20has%20its%20own%20unique%20design%20and%20functionality.&redirect_uri=http%3A%2F%2Ffff.cmiscm.com%2Fclose.html&display=popup